<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLdkv313\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLdkv313/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLdkv313.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLdkv313\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLdkv313\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ldkv313',
    'container.build_id' => 'e6c427a0',
    'container.build_time' => 1581228371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLdkv313');
