<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxA08c5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxA08c5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxA08c5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxA08c5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxA08c5\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxA08c5',
    'container.build_id' => '90f3187c',
    'container.build_time' => 1582348710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxA08c5');
